# Generated by Django 3.2 on 2021-04-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('idEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Emisor', to='nucleo.usuario', verbose_name='Usuario Emisor')),
                ('idReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Receptor', to='nucleo.usuario', verbose_name='Usuario Receptor')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=80)),
                ('foto', models.ImageField(upload_to='photos/', verbose_name='Foto')),
                ('biografia', models.TextField(max_length=255)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='photos/', verbose_name='Foto')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='nucleo.cliente', verbose_name='Cliente')),
                ('idEspecialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especialista', to='nucleo.especialista', verbose_name='Especialista')),
            ],
        ),
    ]
