# Generated by Django 3.2 on 2021-05-31 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20210519_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
