# Generated by Django 3.2 on 2021-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20210415_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
