# Generated by Django 3.2 on 2021-04-21 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0003_auto_20210415_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='idEmisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Emisor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Emisor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='idReceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Receptor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Receptor'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
