# Generated by Django 3.2 on 2021-06-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_mensaje_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espelicalista', to=settings.AUTH_USER_MODEL),
        ),
    ]
